from pptx import Presentation
from pptx.util import Inches

def inspect(ppt_path, slide_indices):
    prs = Presentation(ppt_path)
    for idx in slide_indices:
        if idx >= len(prs.slides):
            print(f"Slide {idx} not found")
            continue
            
        slide = prs.slides[idx]
        print(f"\n--- Slide {idx} (Index {idx}) ---")
        for i, shape in enumerate(slide.shapes):
            top_in = shape.top / 914400
            left_in = shape.left / 914400
            height_in = shape.height / 914400
            name = shape.name
            text = ""
            if shape.has_text_frame:
                text = shape.text_frame.text.strip()[:50]
            elif shape.has_table:
                text = f"Table: {len(shape.table.rows)} rows. Cell(0,0): {shape.table.cell(0,0).text}"
            
            print(f"Shape {i}: Name='{name}', Type={shape.shape_type}, Top={top_in:.2f}, Left={left_in:.2f}, Height={height_in:.2f}, Text='{text}'")

if __name__ == "__main__":
    # Inspect the file generated by the user
    inspect("tejomaya_filled_20251121_111343.pptx", [4, 5])
